name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Mono
      run: sudo apt-get -y install mono-runtime mono-mcs libmono-system-runtime-serialization4.0-cil fakeroot

    - name: Install XUnit
      run: |
        nuget install xunit -Version 1.9.2 -OutputDirectory testrunner
        nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
        nuget install xunit.extensions -Version 1.9.2 -OutputDirectory testrunner

    - name: Run test suite
      run: |
        mcs --version
        cp testrunner/xunit.1.9.2/lib/net20/xunit.dll .
        cp testrunner/xunit.extensions.1.9.2/lib/net20/xunit.extensions.dll .
        mcs src/xp.runner/TPut.cs src/xp.runner/AssemblyInfo.cs -target:exe -main:Xp.Runners.TPut -out:tput.exe
        mcs -r:System.Runtime.Serialization.dll src/xp.runner/*.cs src/xp.runner/*/*.cs -target:exe -main:Xp.Runners.Xar -out:xar.exe
        mcs -r:System.Runtime.Serialization.dll src/xp.runner/*.cs src/xp.runner/*/*.cs -target:exe -main:Xp.Runners.Xp -out:xp.exe
        mcs -r:System.Runtime.Serialization.dll -r:xunit.dll -r:xunit.extensions.dll src/xp.runner/*.cs src/xp.runner/*/*.cs src/xp.runner.test/*.cs -target:library -out:tests.dll
        mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe tests.dll
        mono ./xp.exe list

    - name: Bundle entrypoint
      run: sh .github/workflows/bundle.sh

    - name: Debian package
      run: sh .github/workflows/generic.sh
      env:
        BALTO_REPO_TOKEN: ${{secrets.BALTO_REPO_TOKEN}}

    - name: Generic package
      run: sh .github/workflows/generic.sh
      env:
        BALTO_REPO_TOKEN: ${{secrets.BALTO_REPO_TOKEN}}
